version: ~> 1.0
os: osx
osx_image: xcode12.2

language: cpp
compiler:
    - clang

before_install:
    - export PATH=$PATH:/Library/Frameworks/Python.framework/Versions/3.7/bin
    - curl -OL https://www.python.org/ftp/python/3.7.6/python-3.7.6-macosx10.9.pkg
      && sudo installer -pkg python-3.7.6-macosx10.9.pkg -target /
      && pip3 install conan
      && conan config install https://vuo.org/sites/default/files/conan-macos.zip

install:
    - conan user

script:
    - conan create . vuo/stable
      && conan upload --remote vuo --all --no-overwrite all --confirm macos-sdk/*
